<div class="grid gap-5 sm:grid-cols-2">
    <label class="block text-sm font-semibold text-stone-700">Category<select name="category_id" required class="mt-1.5 block w-full rounded-lg border-stone-300 bg-white py-2.5 text-sm focus:border-amber-600 focus:ring-amber-600"><option value="">Choose category</option>@foreach ($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $product?->category_id) == $category->id)>{{ $category->name }}</option>@endforeach</select></label>
    <label class="block text-sm font-semibold text-stone-700">Product name<input name="name" value="{{ old('name', $product?->name) }}" required class="mt-1.5 block w-full rounded-lg border-stone-300 py-2.5 text-sm focus:border-amber-600 focus:ring-amber-600"></label>
</div>
<label class="block text-sm font-semibold text-stone-700">Description<textarea name="description" rows="3" class="mt-1.5 block w-full rounded-lg border-stone-300 text-sm focus:border-amber-600 focus:ring-amber-600">{{ old('description', $product?->description) }}</textarea></label>
<div class="grid gap-5 sm:grid-cols-3">
    <label class="block text-sm font-semibold text-stone-700">Price<input type="number" step="0.01" min="0" name="price" value="{{ old('price', $product?->price) }}" required class="mt-1.5 block w-full rounded-lg border-stone-300 py-2.5 text-sm"></label>
    <label class="block text-sm font-semibold text-stone-700">Stock quantity<input type="number" min="0" name="stock_quantity" value="{{ old('stock_quantity', $product?->stock_quantity ?? 0) }}" required class="mt-1.5 block w-full rounded-lg border-stone-300 py-2.5 text-sm"></label>
    <label class="block text-sm font-semibold text-stone-700">Low-stock alert<input type="number" min="0" name="low_stock_threshold" value="{{ old('low_stock_threshold', $product?->low_stock_threshold ?? 5) }}" required class="mt-1.5 block w-full rounded-lg border-stone-300 py-2.5 text-sm"></label>
</div>
<div class="flex flex-wrap gap-5 text-sm font-semibold text-stone-700"><label class="inline-flex items-center gap-2"><input type="checkbox" name="is_seasonal" value="1" @checked(old('is_seasonal', $product?->is_seasonal)) class="rounded border-stone-300 text-amber-700 focus:ring-amber-600"> Seasonal product</label><label class="inline-flex items-center gap-2"><input type="checkbox" name="tracks_inventory" value="1" @checked(old('tracks_inventory', $product?->tracks_inventory)) class="rounded border-stone-300 text-amber-700 focus:ring-amber-600"> Track inventory</label></div>
<div class="border-t border-stone-200 pt-5"><div class="flex items-center justify-between"><div><h2 class="font-bold text-stone-950">Modifiers</h2><p class="text-sm text-stone-500">Examples: Size / Large, Milk / Oat Milk, Extra / Extra Shot.</p></div><button type="button" id="add-option" class="rounded-lg border border-stone-300 px-3 py-2 text-sm font-semibold text-stone-700">Add modifier</button></div><div id="options" class="mt-4 space-y-3">@foreach ($product?->productOptions ?? [] as $index => $option)<div class="option-row grid gap-3 sm:grid-cols-[1fr_1fr_8rem_auto]"><input name="options[{{ $index }}][option_type]" value="{{ $option->option_type }}" placeholder="Type" class="rounded-lg border-stone-300 text-sm"><input name="options[{{ $index }}][name]" value="{{ $option->name }}" placeholder="Name" class="rounded-lg border-stone-300 text-sm"><input type="number" step="0.01" min="0" name="options[{{ $index }}][additional_price]" value="{{ $option->additional_price }}" placeholder="Price" class="rounded-lg border-stone-300 text-sm"><button type="button" class="remove-option rounded-lg border border-red-200 px-3 text-sm text-red-700">Remove</button></div>@endforeach</div></div>
<script>
(() => { const list = document.getElementById('options'); const add = document.getElementById('add-option'); let index = {{ count($product?->productOptions ?? []) }}; add.addEventListener('click', () => { const row = document.createElement('div'); row.className = 'option-row grid gap-3 sm:grid-cols-[1fr_1fr_8rem_auto]'; row.innerHTML = `<input name="options[${index}][option_type]" placeholder="Type" class="rounded-lg border-stone-300 text-sm"><input name="options[${index}][name]" placeholder="Name" class="rounded-lg border-stone-300 text-sm"><input type="number" step="0.01" min="0" name="options[${index}][additional_price]" placeholder="Price" value="0" class="rounded-lg border-stone-300 text-sm"><button type="button" class="remove-option rounded-lg border border-red-200 px-3 text-sm text-red-700">Remove</button>`; list.appendChild(row); index++; }); list.addEventListener('click', (event) => { if (event.target.classList.contains('remove-option')) event.target.closest('.option-row').remove(); }); })();
</script>
